package com.dtmarl.failure;

public class FailureEvent {

    public enum Type {
        HOST_FAILURE,
        OVERLOAD_START,
        OVERLOAD_END,
        // Progressive host degradation (HostDegradationManager). Only
        // HOST_FAILURE counts as a failure for labelling purposes; the three
        // below are lifecycle markers used for validation and analysis.
        HOST_FAULT_ONSET,
        HOST_DEGRADATION_START,
        HOST_CRITICAL,
        HOST_RECOVERED,
        NETWORK_FAILURE,
        NETWORK_RECOVERED,
        LINK_DEGRADED_START,
        LINK_DEGRADED_END,
        CYBER_ATTACK_START,
        CYBER_ATTACK_END,
        DEVICE_DROPOUT,
        DEVICE_BATTERY_DEPLETED,
        DEVICE_SENSOR_FAULT
    }

    public enum Cause {
        SCHEDULED,
        RANDOM,
        SYSTEM,
        ATTACK,
        // Accumulated wear crossed the failure hazard - the cause of every
        // host failure generated by HostDegradationManager.
        WEAR,
        REPAIR
    }

    private final int nodeId;
    private final double time;
    private final Type type;
    private final Cause cause;
    private final double cpuAtEvent;

    public FailureEvent(int nodeId, double time, Type type, Cause cause, double cpuAtEvent) {
        this.nodeId = nodeId;
        this.time = time;
        this.type = type;
        this.cause = cause;
        this.cpuAtEvent = cpuAtEvent;
    }

    public int getNodeId() {
        return nodeId;
    }

    public double getTime() {
        return time;
    }

    public Type getType() {
        return type;
    }

    public Cause getCause() {
        return cause;
    }

    public double getCpuAtEvent() {
        return cpuAtEvent;
    }

    /**
     * One CSV row: time,nodeId,type,cause,cpuAtEvent
     *
     * Note: for DEVICE_* event types, `nodeId` is actually the device
     * ID (not a host ID), and `cpuAtEvent` holds the device's battery
     * level at the moment of the event instead of CPU%. Consumers
     * should always disambiguate by `type`, never by `nodeId` alone,
     * since device IDs and host IDs both start at 0 and can collide.
     */
    public String toCsvRow() {
        return String.format("%.2f,%d,%s,%s,%.2f",
                time, nodeId, type, cause, cpuAtEvent);
    }

    @Override
    public String toString() {
        return "[" + type + "] Node " + nodeId +
                " at t=" + String.format("%.2f", time) +
                "s (cause=" + cause + ", cpu=" + cpuAtEvent + "%)";
    }
}